### ISSUE TITLE
deployment steps

### ISSUE THREAD

**Issue by RobBoyers** [DynamicsNinja/PCF-Gallery-Control#1]
Hi,
I'm struggling to deploy this in my environment. I have imported your solution, added a text field to the form and chosen the 'GalleryFieldControl_Display_Key' custom control (with options set for web, phone, & tablet) but the control doesn't seem to work/do anything on the form.
Am I missing a step? My entity is notes enabled and I have a pdf note attachment in my timeline.
Thanks!

Rob

**Comment by DynamicsNinja** [comment]
At the moment control shows only image (.jpg, .png, .svg) files.

**Comment by RobBoyers** [comment]
Thanks for the reply, pdf support would be awesome. Pretty sure I tried png but could have been because I also had a pdf attachment in the list.

**Comment by DynamicsNinja** [comment]
I tried with a mix of PDFs and PNGs and everything seems fine.

**Comment by Marksatx23** [comment]
I can't seem to get it to work at all for some reason.. I did the same thing Rob did above but it doesn't show up correctly.

**Comment by RobBoyers** [comment]
Is it just the pdf you're struggling with Mark? in my case, the problem was the mimetype wasn't being set correctly in the Logic App I was using to upload the pdf. If I manually uploaded the pdf it was fine.

**Comment by Yocomd** [comment]
Does this actually work with PDFs?  I got it installed just fine, but only see images.

**Comment by DynamicsNinja** [comment]
It only shows image files, PDF preview is not supported in this PCF control.
