### ISSUE TITLE
Excluding logos

### ISSUE THREAD

**Issue by rappen** [DynamicsNinja/PCF-Gallery-Control#2]
Hi - great tool!
When you get email there can typically be a handful of attachments, but most of them are company logos, twitter, linkedin, younameit that are from the email footer.

Having an option to exclude "small" image attachments would be awesome!

**Comment by DynamicsNinja** [comment]
I have added the minimum height/width parameter to the control configuration.

**Comment by rappen** [comment]
Great!
No associated commit - I guess it's this one? https://github.com/DynamicsNinja/PCF-Gallery-Control/commit/5d0e26556f406026dd53d02347f17296dee0b172

**Comment by DynamicsNinja** [comment]
Yes, that's the right commit.
