### ISSUE TITLE
How do you get this to work?

### ISSUE THREAD

**Issue by mmcguinness** [DynamicsNinja/PCF-Gallery-Control#6]
Hi, wondering how to get this to work. All it seems to do is display the label "Notes" where the bound field is.  Am I missing something with the configuration?

![Config](https://user-images.githubusercontent.com/11850300/92409064-3a5bc280-f0f4-11ea-80c3-5c11819aa45f.png)
![Results](https://user-images.githubusercontent.com/11850300/92409065-3af45900-f0f4-11ea-8cbf-2c5e35acf69f.png)

**Comment by DynamicsNinja** [comment]
Is the JPG in notes bigger than 100 x 100 px?

**Comment by mmcguinness** [comment]
Hi Ivan, yes, they are larger. It doesn't seem to matter what values I set for any parameter...jpgs don't display.  I created a PNG in Photoshop and that worked. Jpgs from iPhone aren't displaying.

**Comment by DynamicsNinja** [comment]
There was an issue before when you uploaded the image via canvas app that set the wrong MIME type to the image in the metadata and then it fails to load.

**Comment by mmcguinness** [comment]
This was uploaded from a model driven app. Does the control require a specific MIME type, even if file extension is jpg?

**Comment by DynamicsNinja** [comment]
I'll upload a fix for unknown MIME types.

**Comment by mmcguinness** [comment]
Thanks Ivan, I will give it a try again soon!
